name: Run unit tests

on: push

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: setup node 13.x
        uses: actions/setup-node@v1
        with:
          node-version: '13.x'

      - name: npm install
        run: npm install

      - name: lint
        run: npm run lint

      - name: test
        run: npm test

      - name: build
        run: npm run build
